spring:
  application:
    name: blog-api
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: bloguser
    password: blogpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      key-prefix: "blog-api:"
    cache-names:
      - blacklisted_tokens  # JWT Blacklist cache
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          ssl:
            enable: false
    test-connection: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace,loggers,env
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    tags:
      application: blog-api
      environment: development

tracing:
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
  sampling:
    probability: 1.0

server:
  port: 8080

logging:
  level:
    com.blog.api: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000
  blacklist:
    # Rate limiting configuration
    rate-limit:
      max-per-user-per-hour: 10
    # Cleanup configuration
    cleanup:
      enabled: true
      cron: "0 0 2 * * *"  # Daily at 2 AM
    # Monitoring configuration
    monitoring:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Blog API Security Configuration
blog:
  security:
    email-verification:
      enabled: true
      token-expiration: 24h
      max-attempts-per-hour: 3
    password-reset:
      enabled: true
      token-expiration: 15m
      max-attempts-per-hour: 5
  email:
    enabled: true
    from: "noreply@blogapi.com"
    base-url: "http://localhost:8080"
    templates:
      verification: "email/verification"
      password-reset: "email/password-reset"
      welcome: "email/welcome"
  newsletter:
    confirmation:
      token-expiration: 48h
      max-attempts-per-hour: 3
    unsubscribe:
      token-expiration: 365d
      max-attempts-per-hour: 2
    data-request:
      token-expiration: 7d
      max-attempts-per-day: 1
    cleanup:
      enabled: true
      expired-tokens-cron: "0 0 */6 * * *"  # Every 6 hours
      used-tokens-cron: "0 0 2 * * *"       # Daily at 2 AM
      old-tokens-retention-days: 30